### ISSUE TITLE
I can't see the indentifer form in article

### ISSUE THREAD

**Issue by horaciod** [yasielpv/pkp-ark-pubid#1]
I have a DOI plugin installed is that a problem ? ?

**Comment by yasielpv** [comment]
> I have a DOI plugin installed is that a problem ? ?

Hi @horaciod can you send a picture from the config page of the plugin and the metadata tab of the article

The plugin can use with other pubId plugins such as DOI plugin

**Comment by horaciod** [comment]
![setting](https://user-images.githubusercontent.com/1373814/116761026-ea1bd280-a9ec-11eb-9fc7-97e827dfebaf.png)
![editor](https://user-images.githubusercontent.com/1373814/116761179-4f6fc380-a9ed-11eb-9688-da3d439705bd.png)
version  OJS 3.3.0.5 
there is an error in logs 
`PHP Warning:  Declaration of ARKSettingsForm::execute() should be compatible with Form::execute(...$functionArgs) in /var/www/html/ojs3/plugins/pubIds/ark/classes/form/ARKSettingsForm.inc.php on line 0, referer: https://revistas.uncu.edu.ar/ojs3/index.php/saberesypracticas/management/settings/website`

**Comment by yasielpv** [comment]
@horaciod I fixed the issue in the commit #f4f1d8d and put it in the release [ARK PubId Plugin v1.1 for OJS v3.3](https://github.com/yasielpv/pkp-ark-pubid/releases/download/ojs-3.3/ark.tar.gz). Please re-install the plugin.

**Comment by horaciod** [comment]
> @horaciod I fixed the issue in the commit #f4f1d8d and put it in the release [ARK PubId Plugin v1.1 for OJS v3.3](https://github.com/yasielpv/pkp-ark-pubid/releases/download/ojs-3.3/ark.tar.gz). Please re-install the plugin.

Great job. Is working NOW on 3.3.0.5, 
Thanks a Lot. 

Gracias!!!.  Una vez terminemos la implementación en todas las revistas te avisaré. Gracias.

**Comment by yasielpv** [comment]
@horaciod You are welcome and Thanks you for the feedback. I'm doing the procedure to include the plug-in in the Plugin Gallery of OJS
